### ISSUE TITLE
运行不起来啊

### ISSUE THREAD

**Issue by teapot-py** [burningcl/wechat_jump_hack#11]
wechat_jump_hack/out/production/wechat_jump_hack/imgs/input/0.png
java.lang.NullPointerException
	at com.skyline.wxjumphack.Hack.main(Hack.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by burningcl** [comment]
你没有连上ADB，或者从你的手机拉取图片，太慢了

**Comment by burningcl** [comment]
已处理

**Comment by teapot-py** [comment]
可能是因为手机太慢了，我的那个android是好几年前的旧手机了。。。
