### ISSUE TITLE
在网上查了很多，没解决，大佬求帮助。

### ISSUE THREAD

**Issue by T-Y-H** [burningcl/wechat_jump_hack#38]
Caused by: java.io.IOException: CreateProcess error=5, 拒绝访问。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
centerHit: 0, total: 1

**Comment by GreenVegetables** [comment]
static final String ADB_PATH = "D:\\Android\\android-sdk\\platform-tools\\adb.exe";
路径这个试一下，结尾加上adb.exe

**Comment by liubailin2017** [comment]
用不了. 还是别用了吧.

**Comment by burningcl** [comment]
https://github.com/flutter/flutter-intellij/issues/1015
看看这个？？应该是你的adb文件不可执行或者没有权限执行。
我手上没有windows的机器，所以不太好测试这种情况。

**Comment by Yuukion** [comment]
已解决，假如路径是D:/adb  只需要  修改成 D:/adb/adb.exe  就可以了
