### ISSUE TITLE
系统找不到指定的文件。

### ISSUE THREAD

**Issue by BingoKingCoding** [burningcl/wechat_jump_hack#69]
java.io.FileNotFoundException: D:\work\workspace\wechat_jump_hack\out\production\wechat_jump_hack\imgs\input\1.png (系统找不到指定的文件。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.skyline.wxjumphack.ImgLoader.load(ImgLoader.java:19)
	at com.skyline.wxjumphack.Hack.main(Hack.java:47)

**Comment by burningcl** [comment]
更新代码，几天前搞定了
