### ISSUE TITLE
跑了不到600分，就异常退出了

### ISSUE THREAD

**Issue by littlezan** [burningcl/wechat_jump_hack#7]
```
C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb shell input swipe 400 400 400 400 187
screenshot, file: F:\github\workspace\java\out\production\java\imgs\input\196.png
562, 533
pos, x: 547, y: 1239
find myPos, succ, (547, 1239)
17, 19, 30
58, 59, 66
top, x: 79, y: 480
true
left, x: 78, y: 279
right, x: 278, y: 272
java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	at sun.awt.image.ByteInterleavedRaster.getDataElements(ByteInterleavedRaster.java:318)
	at java.awt.image.BufferedImage.getRGB(BufferedImage.java:917)
	at wxjumphack.WhitePointFinder.find(WhitePointFinder.java:24)
	at wxjumphack.Hack.main(Hack.java:48)

Process finished with exit code 0
```

**Comment by burningcl** [comment]
找白点时，越界了。我以为不会出现。。。。我下班后改一下。

**Comment by littlezan** [comment]
好像是掉下去了，程序还在跑，然后出现了这个异常。
跑了很多次，没有超过1000分的，很多时候，100多分就掉下去了，屏幕分辨率是 1080*1920

**Comment by aikongmeng** [comment]
try起来

**Comment by littlezan** [comment]
很容易跳下去，试了好多次，都是200，300分左右就跳下去了
出错信息 `find nextCenter, fail`
```
C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb shell input swipe 400 400 400 400 1023
screenshot, file: F:\workspace\java\03\we_chat_jump\out\production\we_chat_jump\imgs\input\95.png
-2147483648, 2147483647
find nextCenter, fail
pos, x: 0, y: -2147483648
find myPos, succ, (0, -2147483648)
35, 33, 12
67, 65, 52
left, x: 2147483647, y: 2147483647
right, x: -2147483648, y: 2147483647

Process finished with exit code 0
```

**Comment by burningcl** [comment]
你的机型有点奇怪。。。。是什么手机啊。没找到玩家位置，也没有找到下一步的位置。

**Comment by burningcl** [comment]
你发几张识别失败的图片给我看看

**Comment by ldavinciy** [comment]
1080P 跳跃系数 1.35 跳到1w+ 分了,,,不同分辨率 系数不一样的,720P 据说是2.04 2K 的还不知道

**Comment by littlezan** [comment]
努比亚的手机，测试机，这个手机是有些问题，等我换个手机试试。
那个跳下去的截图不太好截图，有 查看排行榜浮层遮在上面，你看一下：
![device-2018-01-03-165635](https://user-images.githubusercontent.com/5358278/34514885-7743e148-f0aa-11e7-9f73-0cf617f2a7f4.png)

**Comment by burningcl** [comment]
好像有点跳过头了，你自己调整一下弹跳系数，减少一点试试

**Comment by daoxiaomianzi** [comment]
我华为p8青春版跑到了3000多分，比较正常，还有个华为mate9测试机就跑到了100多分就不行了，就不正常了，个人感觉：好像影响的除了分辨率还和屏幕尺寸长宽比例有关，p8青春版是正常的16:9，mate9是18:9

**Comment by littlezan** [comment]
换了一个oppo的，跑了335分，也是跳过头了。
我把系数调小一点再试试看，向20000分冲击。
![device-2018-01-03-173805](https://user-images.githubusercontent.com/5358278/34515461-1b33c956-f0ad-11e7-8b3c-c1ff631db6e7.png)
