### ISSUE TITLE
1

### ISSUE THREAD

**Issue by mwebengineer** [burningcl/wechat_jump_hack#75]
root: /C:/Users/wang/Desktop/wechat_jump_hack-master/out/production/wechat_jump_hack-master/
srcDir: C:\Users\wang\Desktop\wechat_jump_hack-master\out\production\wechat_jump_hack-master\imgs\input
centerHit: 0, total: 1
java.io.IOException: Cannot run program "C:/Users/wang/Desktop/adb": CreateProcess error=5, 拒绝访问。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.skyline.wxjumphack.Hack.main(Hack.java:41)
Caused by: java.io.IOException: CreateProcess error=5, 拒绝访问。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more

Process finished with exit code 0

**Comment by burningcl** [comment]
位置写错了，没有这个文件 。
