### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by DreamFreeLx** [burningcl/wechat_jump_hack#86]
java.io.FileNotFoundException: E:\%e6%96%87%e4%bb%b6\wechat_jump_hack-master\out\production\wechat_jump_hack-master\imgs\input\0.png (系统找不到指定的文件。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.skyline.wxjumphack.ImgLoader.load(ImgLoader.java:19)
	at com.skyline.wxjumphack.Hack.main(Hack.java:47)
报这个错误 是因为连接问题吗 是不是没有截屏图片的原因？
但是我 adb device   能查出设备号 

求大神解答 万分感谢

**Comment by DreamFreeLx** [comment]
问题解决了
就是连接问题 
嗯  很好用 谢谢  大神
